storage: ../tmp/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
  yarn:
    url: https://registry.yarnpkg.com
    cache: true

packages:
  '@nxtensions/*':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

logs:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true
