name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.12
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      pnpm-version: 9
      environment-variables: |
        NX_E2E_CI_CACHE_KEY: e2e-ci-linux
      parallel-commands: |
        pnpm nx-cloud record -- pnpm nx format:check
      parallel-commands-on-agents: |
        pnpm nx affected -t lint test build --parallel=2
      final-commands: |
        pnpm nx affected -t e2e --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.12
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 2
      pnpm-version: 9
