name: Run main branch checks

on:
  push:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: main branch checks
    steps:
      - name: Checkout [main]
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for Nx affected commands
        uses: nrwl/nx-set-shas@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Lint affected projects
        run: yarn nx affected --target=lint --parallel

      - name: Build affected projects
        run: yarn nx affected --target=build --parallel

      - name: Test affected projects
        run: npx nx affected --target=test --parallel
